name: Build Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get package version
        id: version
        uses: zoexx/github-action-json-file-properties@b9f36ce6ee6fe2680cd3c32b2c62e22eade7e590
        with:
          file_path: package.json
          prop_path: version

      - name: Set release names
        run: |
          echo "zipFile=com.starsideup.avatar-license-manager-${{ steps.version.outputs.value }}.zip" >> $GITHUB_ENV
          echo "unityPackage=com.starsideup.avatar-license-manager-${{ steps.version.outputs.value }}.unitypackage" >> $GITHUB_ENV
          echo "version=${{ steps.version.outputs.value }}" >> $GITHUB_ENV

      - name: Create package zip
        run: zip -r "${{ github.workspace }}/${{ env.zipFile }}" . -x ".git/*" ".github/*"

      - name: Track package meta files
        run: find . -name "*.meta" -not -path "./.git/*" -not -path "./.github/*" >> metaList

      - name: Create unitypackage
        uses: pCYSl5EDgo/create-unitypackage@v1.2.3
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList

      - name: Create version tag
        uses: rickstaa/action-create-tag@88dbf7ff6fe2405f8e8f6c6fdfd78829bc631f83
        with:
          tag: "${{ env.version }}"

      - name: Publish release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
            package.json
          tag_name: ${{ env.version }}
